const TYPES = {
    LOGIN_ADMIN_REQUEST: '@@AUTH/LOGIN_ADMIN_REQUEST',
    LOGIN_ADMIN_SUCCESS: '@@AUTH/LOGIN_ADMIN_SUCCESS',
    LOGIN_ADMIN_FAILURE: '@@AUTH/LOGIN_ADMIN_FAILURE',

};

export default TYPES;