const TYPES = {
    LOGIN_ADMIN_REQUEST: '@@AUTH/LOGIN_ADMIN_REQUEST',
    LOGIN_ADMIN_SUCCESS: '@@AUTH/LOGIN_ADMIN_SUCCESS',
    LOGIN_ADMIN_FAILURE: '@@AUTH/LOGIN_ADMIN_FAILURE',

    GET_USERS_REQUEST: '@@USERS/GET_USERS_REQUEST',
    GET_USERS_SUCCESS: '@@USERS/GET_USERS_SUCCESS',
    GET_USERS_FAILURE: '@@USERS/GET_USERS_FAILURE',

    GET_SINGLE_USER_REQUEST: '@@USERS/GET_SINGLE_USER_REQUEST',
    GET_SINGLE_USER_SUCCESS: '@@USERS/GET_SINGLE_USER_SUCCESS',
    GET_SINGLE_USER_FAILURE: '@@USERS/GET_SINGLE_USER_FAILURE',

    ADD_USER_REQUEST: '@@USERS/ADD_USER_REQUEST',
    ADD_USER_SUCCESS: '@@USERS/ADD_USER_SUCCESS',
    ADD_USER_FAILURE: '@@USERS/ADD_USER_FAILURE',

    EDIT_USER_REQUEST: '@@USERS/EDIT_USER_REQUEST',
    EDIT_USER_SUCCESS: '@@USERS/EDIT_USER_SUCCESS',
    EDIT_USER_FAILURE: '@@USERS/EDIT_USER_FAILURE',

    DELETE_USER_REQUEST: '@@USERS/DELETE_USER_REQUEST',
    DELETE_USER_SUCCESS: '@@USERS/DELETE_USER_SUCCESS',
    DELETE_USER_FAILURE: '@@USERS/DELETE_USER_FAILURE',
};

export default TYPES;